'use strict';
window.LanguageDetect = (() => {
  const extMap = {
    js: 'javascript', jsx: 'javascript', mjs: 'javascript', cjs: 'javascript',
    ts: 'typescript', tsx: 'typescript',
    py: 'python', pyw: 'python', pyx: 'python',
    rs: 'rust',
    go: 'go',
    java: 'java',
    kt: 'kotlin', kts: 'kotlin',
    swift: 'swift',
    rb: 'ruby', rbw: 'ruby',
    php: 'php', php3: 'php', php4: 'php', php5: 'php', phtml: 'php',
    c: 'c', h: 'c',
    cpp: 'cpp', cc: 'cpp', cxx: 'cpp', c_pp: 'cpp', hpp: 'cpp', hxx: 'cpp',
    cs: 'csharp',
    html: 'html', htm: 'html', xhtml: 'html',
    css: 'css',
    scss: 'scss', sass: 'scss',
    less: 'less',
    json: 'json', jsonc: 'json',
    json5: 'json',
    yaml: 'yaml', yml: 'yaml',
    toml: 'ini',
    xml: 'xml', svg: 'xml', xsl: 'xml',
    md: 'markdown', mdx: 'markdown', markdown: 'markdown',
    sh: 'shell', bash: 'shell', zsh: 'shell', fish: 'shell',
    ps1: 'powershell', psm1: 'powershell', psd1: 'powershell',
    sql: 'sql',
    r: 'r', rmd: 'r',
    lua: 'lua',
    dart: 'dart',
    zig: 'zig',
    ex: 'elixir', exs: 'elixir',
    erl: 'erlang', hrl: 'erlang',
    hs: 'haskell', lhs: 'haskell',
    ml: 'fsharp', mli: 'fsharp', fs: 'fsharp', fsi: 'fsharp', fsx: 'fsharp',
    clj: 'clojure', cljs: 'clojure', cljc: 'clojure',
    scala: 'scala', sc: 'scala',
    groovy: 'groovy', gvy: 'groovy',
    v: 'v',
    vue: 'html',
    svelte: 'html',
    graphql: 'graphql', gql: 'graphql',
    proto: 'protobuf',
    tf: 'hcl', hcl: 'hcl',
    dockerfile: 'dockerfile',
    makefile: 'makefile', mk: 'makefile',
    ini: 'ini', cfg: 'ini', conf: 'ini',
    env: 'ini',
    log: 'plaintext',
    txt: 'plaintext',
    rst: 'restructuredtext',
    tex: 'latex', ltx: 'latex',
    bat: 'bat', cmd: 'bat',
    vbs: 'vb', vb: 'vb',
    asm: 'asm', s: 'asm',
    wasm: 'wat',
    lock: 'plaintext',
    gitignore: 'plaintext', gitattributes: 'plaintext', editorconfig: 'ini',
    prettierrc: 'json', eslintrc: 'json', babelrc: 'json',
    tsconfig: 'json', jsconfig: 'json',
    pkgbuild: 'shell',
    nim: 'plaintext',
    cr: 'plaintext',
    d: 'plaintext',
    f90: 'plaintext', f95: 'plaintext', f: 'plaintext',
    m: 'objective-c', mm: 'objective-c',
  };

  const nameMap = {
    'dockerfile': 'dockerfile',
    'makefile': 'makefile',
    'gemfile': 'ruby',
    'rakefile': 'ruby',
    'podfile': 'ruby',
    'vagrantfile': 'ruby',
    'guardfile': 'ruby',
    'brewfile': 'ruby',
    'fastfile': 'ruby',
    'appfile': 'ruby',
    'fastlane': 'ruby',
    'procfile': 'shell',
    'jenkinsfile': 'groovy',
    '.gitignore': 'plaintext',
    '.gitattributes': 'plaintext',
    '.editorconfig': 'ini',
    '.nvmrc': 'plaintext',
    '.npmrc': 'ini',
    '.env': 'ini',
    '.babelrc': 'json',
    '.eslintrc': 'json',
    '.prettierrc': 'json',
    'cargo.toml': 'toml',
    'cargo.lock': 'toml',
    'go.mod': 'go',
    'go.sum': 'go',
    'requirements.txt': 'plaintext',
    'pipfile': 'ini',
    'pyproject.toml': 'toml',
    'setup.py': 'python',
    'setup.cfg': 'ini',
    'package.json': 'json',
    'package-lock.json': 'json',
    'yarn.lock': 'plaintext',
    'tsconfig.json': 'json',
  };

  function fromPath(filePath) {
    if (!filePath) return 'plaintext';
    const name = filePath.split(/[/\\]/).pop().toLowerCase();
    if (nameMap[name]) return nameMap[name];
    const ext = name.includes('.') ? name.split('.').pop() : '';
    return extMap[ext] || 'plaintext';
  }

  function getDisplayName(lang) {
    const names = {
      javascript: 'JavaScript', typescript: 'TypeScript',
      python: 'Python', rust: 'Rust', go: 'Go', java: 'Java',
      kotlin: 'Kotlin', swift: 'Swift', ruby: 'Ruby', php: 'PHP',
      c: 'C', cpp: 'C++', csharp: 'C#', html: 'HTML', css: 'CSS',
      scss: 'SCSS', json: 'JSON', yaml: 'YAML', markdown: 'Markdown',
      shell: 'Shell', powershell: 'PowerShell', sql: 'SQL',
      plaintext: 'Plain Text',
    };
    return names[lang] || lang.charAt(0).toUpperCase() + lang.slice(1);
  }

  return { fromPath, getDisplayName };
})();
